/**
 * pass 33 — canonical hadith numbers (the numbers sunnah.com uses in its
 * URLs, e.g. sunnah.com/bukhari:5061).
 *
 * Our content pack lists hadiths in its OWN order (chapters grouped
 * differently), so the array index is NOT the canonical number. These maps
 * (public/hadith-num/<book>.json, generated by text-matching every hadith
 * against the sunnah.com-aligned dataset) give the true number for each of
 * our entries, in pack order.
 */
const cache = new Map<string, Promise<number[]>>();

export function hadithNumbers(book: string): Promise<number[]> {
  let p = cache.get(book);
  if (p) return p;
  p = (async () => {
    const base = typeof window !== 'undefined' ? window.location.pathname.replace(/^(\/deenapp\b).*$/, '$1') : '';
    const r = await fetch(`${base}/hadith-num/${book}.json`);
    const j = (await r.json()) as number[];
    if (!Array.isArray(j) || !j.length) throw new Error('no numbers for ' + book);
    return j;
  })().catch((e) => {
    cache.delete(book);
    throw e;
  });
  cache.set(book, p);
  return p;
}
