import { chromium } from 'playwright-core';
const BASE = 'http://127.0.0.1:8400/deenapp';
const browser = await chromium.launch({ executablePath: '/home/user/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell', args: ['--no-sandbox'] });
const errs = [];
const page = await (await browser.newContext({ viewport: { width: 420, height: 860 } })).newPage();
page.on('pageerror', (e) => errs.push(String(e).slice(0, 160)));
await page.goto(BASE + '/tools/fatwa', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(8000);
const chip = page.locator('text=Ask a Scholar').first();
console.log('chip count:', await chip.count());
await chip.click();
await page.waitForTimeout(2500);
const t = await page.evaluate(() => document.body.innerText.replace(/\s+/g, ' '));
console.log('panel ::', t.slice(0, 420));
console.log('has TITLE input:', /title/i.test(t) ? 'OK' : 'FAIL');
console.log('has details:', /details|question/i.test(t) ? 'OK' : 'FAIL');
console.log('has bonus points:', /bonus|DeenPoints/i.test(t) ? 'OK' : 'FAIL');
console.log('ERRORS:', errs.length ? errs.join('\n') : 'none');
await browser.close();
