import { chromium } from 'playwright-core';
const BASE = 'http://app.deenlink.org';
const browser = await chromium.launch({ executablePath: '/home/user/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell', args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 420, height: 860 } });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR:', String(e).slice(0, 150)));
await page.goto(BASE + '/login', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(4500);
const inputs = await page.$$('input');
await inputs[0].fill('p74x1788723499095@t.co');
await inputs[1].fill('Str0ngPass!23');
await page.getByText('Sign In', { exact: true }).first().click();
await page.waitForTimeout(6000);
await page.goto(BASE + '/profile/p74y1788723499095', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(5000);
const pill = page.getByText(/^Message$/).first();
console.log('message pill count:', await page.getByText(/^Message$/).count());
await pill.click();
await page.waitForTimeout(3000);
console.log('URL:', page.url().replace(BASE, ''));
console.log('textareas:', (await page.$$('textarea')).length, 'inputs:', (await page.$$('input')).length);
console.log('BODY:', (await page.evaluate(() => document.body.innerText.replace(/\s+/g, ' '))).slice(0, 220));
await page.waitForTimeout(3000);
console.log('after 3s more — textareas:', (await page.$$('textarea')).length, 'inputs:', (await page.$$('input')).length);
console.log('BODY2:', (await page.evaluate(() => document.body.innerText.replace(/\s+/g, ' '))).slice(0, 220));
await browser.close();
